dist: xenial

language: minimal

env:
  global:
    - REPO=docksal/runner
    - VERSION=curl-git
    - HOST_UID=$(id -u)
    - HOST_GID=$(id -g)

install:
  - curl -fsSL get.docksal.io | sh
  - fin version
  - fin sysinfo

script:
  - make && make test

after_failure:
  - make logs
