language: generic

services:
  - docker

env:
  global:
    - REPO=docksal/runner
    - VERSION=curl-git

install:
  - curl -fsSL get.docksal.io | sh
  - fin version
  - fin sysinfo

script:
  - make && make test

after_failure:
  - make logs
